name: "Run unit tests"

on: [push]

jobs:
  test:
    name: "Test on ${{ matrix.php }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
        experimental: [false]
        include:
          - php: '8.0'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension-csv: exif,json,mbstring
          coverage: pcov

      - name: Get user-level Composer cache
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ matrix.package-release }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-${{ matrix.package-release }}-${{ env.cache-name }}-
            composer-${{ matrix.php }}-${{ matrix.package-release }}-
            composer-${{ matrix.php }}-
            composer-

      - name: Login for Laravel Nova
        run: composer config http-basic.nova.laravel.com "${NOVA_USERNAME}" "${NOVA_TOKEN}"
        env:
          NOVA_USERNAME: ${{ secrets.NovaUsername }}
          NOVA_TOKEN: ${{ secrets.NovaApiToken }}

      - name: Pretend to be latest PHP
        if: matrix.experimental
        run: composer config platform.php 7.4.8

      - name: Don't constrain versions on 7.x
        if: matrix.php != '8.0'
        run: composer config --unset platform.php

      - name: Install composer dependencies
        run: |
          composer update --no-suggest --no-progress --no-interaction

      - name: Run unit tests
        if: matrix.php == '8.0'
        run: vendor/bin/phpunit
